enum E_EMPLOYEES {
    FILL_EMPLOYEES = 'FILL_EMPLOYEES',
    FILL_SELECT_EMPLOYEES = 'FILL_SELECT_EMPLOYEES',
    SELECT_EMPLOYEE = 'SELECT_EMPLOYEE',
    UNSELECT_EMPLOYEE = 'UNSELECT_EMPLOYEE',

    FETCH_EMPLOYEES_ASYNC = 'FETCH_EMPLOYEES_ASYNC',
}

export {
    E_EMPLOYEES
}
